services:
  - type: web
    name: visao-computacional-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT api:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
